project:
    project_name: passive data project
    description: Integrating code for passive data pipeline that has been used ART-pilot study
    version: 0.0

input_data:
    data_location: mock
    local_directory: mockdata/mockdata
    data_format: csv

configurations:
    df_type: 'pandas'

features:
    - location: 'https://github.com/RADAR-base-Analytics/passivedatapipeline'
      branch: 'dev'
      feature_groups:
        - PassiveDataFeatures
      feature_names:
        - all

output_data:
    output_location: local
    local_directory: output/passive_output
    data_format: csv
    compress: false
